# Environment that does not use a GPU
name: examol
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*
  - pandas==1.*
  - xtb-python==22.*
  - scikit-learn>=1
  - pymongo
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
    - tensorflow-cpu
    - nfp
    - -e ..
