# Environment that uses a locally-installed CUDA 11.8
#  Installs packages needed for all features
name: examol
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*
  - pandas==1.*
  - xtb-python==22.*
  - scikit-learn>=1
  - pymongo
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
    # Need TF for NFP MPNNs
    - tensorflow
    - nfp
    
    # Need torch for BOTorch
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.1+cu118
    - -e ..[botorch,test]
