# Environment that does not use a GPU
#  Installs packages needed for all features
name: examol
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.*
  - pandas==1.*
  - xtb-python==22.*
  - scikit-learn>=1
  - pymongo
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
    # Need TF for NFP MPNNs
    - tensorflow-cpu
    - nfp
    
    # Need torch for BOTorch
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - pytorch==2.0.1
    - -e ..
