# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on: [push, pull_request]

permissions:
  contents: read
  
defaults:
  run:
    shell: bash -el {0}  # Lets conda work

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: envs/environment-cpu.yml
        mamba-version: "*"
    - name: Install test dependencies
      run: |
        pip install -e .[test]
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 examol tests examples
    - name: Add quantum chemistry tools
      run: |
        sudo apt-get update
        sudo apt install -y cp2k
    - name: Test with pytest
      run: pytest --cov=examol --timeout=300 tests
    - name: Coveralls
      run: |
        pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
